import type { Dictionary } from "../config";

export const en: Dictionary = {
  seo: { title: "COMB / 001 — The Entanglement", description: "An experimental artwork about memories that overlap, linger, and cannot be entirely separated." },
  nav: { main: "Main navigation", language: "Language", concept: "Concept", principles: "Five principles", field: "Memory field", remains: "What remains", about: "About", skip: "Skip to content" },
  entrance: { auxiliary: "A study of memory's entangled parts", alias: "The comb", edition: "COMB / 001 — The Entanglement", line: "Some memories were never separate.", enter: "Enter the Memory", scroll: "Scroll to unfold", soundOn: "Sound on", soundOff: "Sound off" },
  concept: {
    kicker: "01 / THE CONCEPT", title: "The things we cannot pull apart.", lead: "Some memories were never separate.",
    paragraphs: ["We do not remember in neat, isolated events. A person, a sound, a room, and a feeling can seep into one another.", "COMB attends to the parts that have lost their edges. A song may belong to several summers. A feeling may remain long after the event that gave rise to it is gone."],
    combLine: "To comb is not necessarily to separate.", open: "Read the Concept", close: "Close the Concept", statementTitle: "Project statement",
    statement: ["COMB is an experimental interactive artwork about entanglement in subjective memory: the point at which different remembered elements share an atmosphere and can no longer be returned intact to separate events.", "Its starting point was a dream of a stream of consciousness film about human memory and an accompanying app called COMB. In the dream, the phrase ‘reflecting the parts of human memory that stick together’ seemed immediately clear. On waking, the full meaning could no longer be put into words. This work is an interpretation of that remainder, not a reconstruction of the dream.", "Through image, sound, text, and interaction, COMB offers a set of designed encounters with association, overlap, and residue. The visitor's choices alter which fragments touch and what traces they leave. The work aims to make a condition perceptible, while leaving room for meanings that resist a complete explanation."],
    boundary: "COMB does not read, identify, diagnose, or objectively reconstruct anyone's real memories. Entanglement is an artistic term here; it does not claim a scientific correspondence with quantum physics."
  },
  principles: { kicker: "02 / FIVE PRINCIPLES", title: "Five ways memory holds together.", items: [
    { name: "Association", definition: "Distance in memory is not distance in time.", detail: "An afternoon from years ago may feel closer than yesterday. Sounds, places, and gestures draw moments toward one another." },
    { name: "Entanglement", definition: "A connection can become a shared texture.", detail: "A person can come to stand for an entire season; a song can carry several stages of a life at once." },
    { name: "Residue", definition: "The event fades. Its feeling stays.", detail: "Sometimes the scene can no longer be retrieved, yet its warmth, tension, or color remains." },
    { name: "Coexistence", definition: "Several versions of a past can remain true to us.", detail: "A later understanding does not have to erase what we first felt. Both can inhabit the same memory." },
    { name: "Shared Memory", definition: "A moment together becomes another memory.", detail: "Two people can watch the same work and follow different private associations. The act of watching together leaves a new trace." }
  ] },
  field: {
    kicker: "03 / MEMORY FIELD", title: "Follow what draws near.", intro: "These fragments are composed for this artwork. They are not records of your past. Move among them and let two touch; each encounter leaves a different trace.",
    instruction: "Drag one fragment onto another, or select two to bring them together.", touchInstruction: "Touch one fragment, then another. You can also drag between them.", keyboardInstruction: "Tab to a fragment. Press Enter or Space to select it, then choose another.", linkLabel: "Entangle fragments", linked: "A connection remains", selected: "First fragment selected", clearSelection: "Cancel selection", removeLink: "Remove this connection", reset: "Clear all connections", count: "connections", relationTitle: "An echo between them", relationEmpty: "Nothing has touched yet. The field is waiting.", relationActive: "Two fragments now share a trace. Their original words remain, but the space between them has changed.", residue: "The trace remains after attention moves away.",
    types: { scene: "Scene", person: "Person", sound: "Sound", feeling: "Feeling", sentence: "Fragment" },
    fragments: ["A room I no longer remember.", "The song from another summer.", "A familiar voice without a face.", "The light at four in the afternoon.", "The street after rain.", "Someone turning to leave.", "The warmth of a coat I cannot place.", "A name caught in a melody.", "The last window still lit.", "A silence after laughter.", "The scent of an unfamiliar home.", "A train passing without stopping.", "The same blue in two cities.", "An unfinished sentence at the door.", "The sound of dishes from another room.", "A hand briefly on my shoulder.", "A season that belongs to no year.", "The shape of a forgotten goodbye.", "A morning remembered as evening.", "The feeling, without its cause."],
    echoes: ["For a moment, they belong to the same place.", "A sound carries the color of another scene.", "The edges soften; neither fragment disappears.", "Something passes between them and stays.", "One memory lends its weather to the other.", "Their distance was never measured in years.", "The feeling arrives before the story.", "Two versions of the moment remain."],
    accessibility: "Interactive memory field. Select two fragments to connect them. Connections are also listed below the field."
  },
  remains: { kicker: "04 / WHAT REMAINS", title: "What remains?", intro: "A sentence can hold what the field leaves behind. It belongs to you alone, here in this browser.", label: "Your trace", placeholder: "I remember the feeling, but not the event.", save: "Keep this trace", saved: "Saved in this browser", delete: "Delete my trace", exportTxt: "Export TXT", exportJson: "Export JSON", privacy: "Your words stay in this browser. They are not automatically uploaded. Clearing browser data may erase them; you can delete or export them at any time.", missing: "Write something before saving.", storageError: "This browser could not save the trace. You can still copy your words.", deleteConfirm: "Your trace was deleted from this browser." },
  about: { kicker: "05 / ABOUT COMB", title: "A dream, and what followed it.", original: "Original Dream Concept", originalText: ["In a dream, a production company released stream of consciousness films. One installment concerned human memory, with music, people, places, and fragments that resisted explanation.", "An accompanying app was called COMB / 梳子. Its surviving description was: ‘reflecting the parts of human memory that stick together.’ In the dream, this seemed understandable. On waking, its full meaning could not be recovered."], interpretation: "Artistic Interpretation", interpretationText: ["This site develops that surviving phrase into an artwork. The five principles, the fragments, and their interactions are later creative choices, not facts remembered from the dream.", "A comb ordinarily separates tangled hair. Here, combing follows the grain of memory so that its entanglements become visible. To comb is not necessarily to separate."], attribution: "COMB / 001 — The Entanglement" },
  footer: { line: "Some memories were never separate.", local: "An experience held in this browser", top: "Return to entrance" }
};
